//
//  Constants.h
//  Listen
//
//  Created by Dai Hovey on 06/12/2012.
//  Copyright (c) 2012 14lox. All rights reserved.
//

#define CELL_HEIGHT 75.0f
#define SEARCH_HEADER_CELL_HEIGHT 50.0f
#define PLAYER_HEIGHT 44.0f
#define TOP_NAVIGATION_HEIGHT 46.5f
#define TOP_NAV_ICON_Y_AXIS_DIFF 4.25f

#define PINK_COLOUR 0xf5969c
#define RED_COLOUR 0xff6666
#define GREY_COLOUR 0x6d6e71
#define DARK_GREY_COLOUR 0x363636
#define BACKGROUND_COLOUR 0x111111
#define WHITE_COLOUR 0xFFFFFF

#define NOTIFICATION_CURRENT_TRACK_UPDATE @"NOTIFICATION_CURRENT_TRACK_UPDATE"
#define NOTIFICATION_PLAY_PAUSE_TOGGLE @"NOTIFICATION_PLAY_PAUSE_TOGGLE"
#define NOTIFICATION_TRACK_REACHED_END @"NOTIFICATION_TRACK_REACHED_END"
#define NOTIFICATION_PLAYER_IS_EMPTY @"NOTIFICATION_PLAYER_IS_EMPTY"
#define NOTIFICATION_PLAYER_HAS_TRACKS @"NOTIFICATION_PLAYER_HAS_TRACKS"
#define NOTIFICATION_TRACK_ADDED @"NOTIFICATION_TRACK_ADDED"
#define NOTIFICATION_SHOW_SEARCHTABLE @"NOTIFICATION_SHOW_SEARCHTABLE"
#define NOTIFICATION_TRACK_DELETED @"NOTIFICATION_TRACK_DELETED"
#define NOTIFICATION_PLAYLIST_ARRAY_MODIFIED @"NOTIFICATION_PLAYLIST_ARRAY_MODIFIED"
#define NOTIFICATION_SCROLL_TABLE_TO_TOP @"NOTIFICATION_SCROLL_TABLE_TO_TOP"
#define NOTIFICATION_TIME_CHANGED @"NOTIFICATION_TIME_CHANGED"

#define SHOW_TOP_NAVIGATION @"SHOW_TOP_NAVIGATION"

// INSTRUCTION NAVIGATION

#define NOTIFICATION___INSTRUCTION_FIRST_STEP_COMPLETE @"NOTIFICATION___INSTRUCTION_FIRST_STEP_COMPLETE"
#define NOTIFICATION___INSTRUCTION_SECOND_STEP_COMPLETE @"NOTIFICATION___INSTRUCTION_SECOND_STEP_COMPLETE"
#define NOTIFICATION___INSTRUCTION_THIRD_STEP_COMPLETE @"NOTIFICATION___INSTRUCTION_THIRD_STEP_COMPLETE"
#define NOTIFICATION___INSTRUCTION_FOURTH_STEP_COMPLETE @"NOTIFICATION___INSTRUCTION_FOURTH_STEP_COMPLETE"
#define NOTIFICATION___INSTRUCTION_FLASH_PLAYLIST_ICON @"NOTIFICATION___INSTRUCTION_FLASH_PLAYLIST_ICON"
#define NOTIFICATION___INSTRUCTION__STOP__FLASH_PLAYLIST_ICON @"NOTIFICATION___INSTRUCTION__STOP__FLASH_PLAYLIST_ICON"

// Media meta data keys

#define MEDIA_FULL_STRING @"MEDIA_FULL_STRING"
#define MEDIA_TRACK_STRING @"MEDIA_TRACK_STRING"
#define MEDIA_ARTIST_STRING @"MEDIA_ARTIST_STRING"
#define MEDIA_ALBUM_STRING @"MEDIA_ALBUM_STRING"

#define SONG_INDEX @"SONG_INDEX"
#define SONG_OBJECT @"SONG_OBJECT"
#define REACHED_END @"REACHED_END"

#define SCROLL_START @"SCROLL_START"
#define SCROLL_END @"SCROLL_END"

#define PULL_DOWN_VELOCITY 3000.0f

// Saving playlist keys

#define SAVE_TRACKS @"playlist_tracks"
#define SAVE_NAME @"playlist_name"
#define SAVE_MODIFIED @"playlist_modified"
#define SAVE_CURRENT_TRACK @"playlist_current_track"
#define SAVE_CURRENT_TRACK_TIME @"playlist_current_track_time"

// Reordering tracks
#define REORDER_DUMMY_TRACK @"REORDER_DUMMY_TRACK"
#define REORDER_CURRENT_TRACK @"REORDER_CURRENT_TRACK"

#define INTRODUCTION_DISPLAYED @"INTRODUCTION_DISPLAYED"